### PR TITLE
Add Scan.split_by_steps() method

### PR DESCRIPTION
**Pull request by takluyver**
To split any of our objects with a `.select_trains()` method, as well as suitable DataArrays. E.g. we could have used this recently for FXE to split JUNGFRAU data into scan steps before loading it.

This is pretty trivial to do without an extra method, but it seems like a nice convenience, and I think it fits neatly with `bin_by_steps`. I also hope that we can later optimise it to avoid the N-squared performance we had with `.split_trains()` on long runs in the past.

### CODE REVIEW

**Comment by philsmt** [comment]
`TrainSelectable` protocol 👀 

LGTM!

**Review by philsmt — APPROVED** [review]

**Comment by takluyver** [comment]
Thanks!

Do you know if the generated data for tests includes any scan-like data to test with? I added to one of the existing tests, but it's a bit useless since there's no real data, so zero scan steps to work with.

**Comment by philsmt** [comment]
Unfortunately I'm not aware of any. In EXtra-data I added data in individual tests, while in EXtra there's only what you can see in `mockdata`. FWIW, I will be in need of a `Motor` with actual data for the `OpticalLaserDelay` tests as well.

**Comment by takluyver** [comment]
I've added some simple scan-like data for `MOTOR/MCMOTORYFACE.actualPosition`, to test this better.

**Comment by JamesWrigley** [comment]
FWIW the tests already use `Scan._mkscan()` to generate fake scans: https://github.com/European-XFEL/EXtra/blob/6f03c90fd903c5913db7234dd6ec0e68a9416182/src/extra/components/scan.py#L308

**Comment by takluyver** [comment]
Thanks! I half spotted that, but I wanted to make the test a bit more realistic, with data coming from files, and to have the train IDs line up with the rest of the run for splitting it.

**Pull request merged**
