### PR TITLE
fix(dependency): add tabulate (used in markdown_table)

### PR DESCRIPTION
**Pull request by kakhahmed**
The calibration method [markdown_table](https://github.com/European-XFEL/EXtra/blob/1c3febdb8ec7340898ae0b55e4c8f9e264bfaa5c/src/extra/calibration.py#L811) imports tabulate.

This MR includes the missing dependency for tabulate

### CODE REVIEW

**Comment by tmichela** [comment]
I'm surprised this did not break tests 🤔 
LGTM

**Comment by kakhahmed** [comment]
> I'm surprised this did not break tests 🤔 LGTM

Thank you @tmichela for the review.

The method that imports this library doesn't have tests.

BTW I don't have access to merge. So please merge at your convenience.

**Comment by philsmt** [comment]
> BTW I don't have access to merge. So please merge at your convenience.

Fixed that on the repository level, please ask @tmichela or @takluyver to be added to the organization

**Comment by kakhahmed** [comment]
Thank you both, I have access now

**Comment by takluyver** [comment]
Thanks, LGTM

**Pull request merged**
