### PR TITLE
Deprecate the `get_` prefix from some method names

### PR DESCRIPTION
**Pull request by JamesWrigley**
See: https://github.com/European-XFEL/EXtra/pull/53#issuecomment-1903955087

### CODE REVIEW

**Comment by philsmt** [comment]
LGTM, thanks :pray: 

Are we removing those for the next run (i.e. 2024/2)?

**Comment by JamesWrigley** [comment]
Yeah, I think next run is reasonable since I assume there's not too many uses of this in the wild yet :+1:

**Comment by tmichela** [comment]
you mean current run (202401), right?

**Comment by philsmt** [comment]
Now, I mean removing it at the beginning of 2024/2. It seems prudent to have the deprecation warning to at least appear for a run.

**Comment by JamesWrigley** [comment]
(or even a year if the deprecated thing is widely used, since many users only come around once a year)

**Comment by tmichela** [comment]
👍

**Pull request merged**
