### PR TITLE
Final packaging touches

### PR DESCRIPTION
**Pull request by philsmt**
As discussed this changes to a calendar-based numbering scheme, and potentially any future change we need on the way to first release.

@JamesWrigley @takluyver @tmichela

### CODE REVIEW

**Comment by JamesWrigley** [comment]
LGTM! We should also replace the initial tag.

**Comment by RobertRosca** [comment]
O hello I did something having not seen this... oopsie

**Comment by takluyver** [comment]
LGTM

**Comment by tmichela** [comment]
LGTM

**Pull request merged**
